# Generated by Django 5.2.5 on 2025-08-21 12:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fleet', '0001_initial'),
        ('policies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('PM', 'Preventive Maintenance'), ('CM', 'Corrective Maintenance'), ('INSPECTION', 'Inspection')], default='PM', max_length=16)),
                ('priority', models.CharField(default='P2', max_length=4)),
                ('due_by', models.DateTimeField()),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='planned', max_length=16)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_workorders', to=settings.AUTH_USER_MODEL)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_workorders', to=settings.AUTH_USER_MODEL)),
                ('policy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='policies.maintenancepolicy')),
                ('robot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fleet.robot')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fleet.site')),
            ],
        ),
    ]
