services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: maint
      POSTGRES_USER: maint
      POSTGRES_PASSWORD: maint
    ports:
      - "5432:5432"
  redis:
    image: redis:7
    ports:
      - "6379:6379"
