# Generated by Django 5.2.5 on 2025-09-11 19:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0001_initial'),
        ('workorders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklistrun',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='checklistrun',
            name='signed_at',
        ),
        migrations.AddField(
            model_name='checklistrun',
            name='tools_used',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='checklisttemplate',
            name='kit',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='checklistrun',
            name='photos',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='checklistrun',
            name='responses',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='checklistrun',
            name='signed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='checklistrun',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='checklistrun',
            name='work_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='workorders.workorder'),
        ),
        migrations.AlterField(
            model_name='checklisttemplate',
            name='items',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
