# Generated by Django 5.2.5 on 2025-09-11 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0002_remove_checklistrun_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checklistrun',
            old_name='updated_at',
            new_name='created_at',
        ),
    ]
