# Generated by Django 5.2.5 on 2025-10-30 20:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0003_rename_updated_at_checklistrun_created_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checklistrun',
            options={'ordering': ('-started_at',)},
        ),
        migrations.AlterModelOptions(
            name='checklisttemplate',
            options={'ordering': ('name',)},
        ),
        migrations.RemoveField(
            model_name='checklistrun',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='checklistrun',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='checklistrun',
            name='photos',
        ),
        migrations.RemoveField(
            model_name='checklistrun',
            name='responses',
        ),
        migrations.RemoveField(
            model_name='checklistrun',
            name='tools_used',
        ),
        migrations.RemoveField(
            model_name='checklistrun',
            name='work_order',
        ),
        migrations.RemoveField(
            model_name='checklisttemplate',
            name='checklist_id',
        ),
        migrations.RemoveField(
            model_name='checklisttemplate',
            name='items',
        ),
        migrations.RemoveField(
            model_name='checklisttemplate',
            name='kit',
        ),
        migrations.RemoveField(
            model_name='checklisttemplate',
            name='requires_photos',
        ),
        migrations.RemoveField(
            model_name='checklisttemplate',
            name='version',
        ),
        migrations.AddField(
            model_name='checklistrun',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='checklistrun',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_checklist_runs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='checklistrun',
            name='started_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='checklisttemplate',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='checklistrun',
            name='signed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signed_checklist_runs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='checklistrun',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='checklists.checklisttemplate'),
        ),
        migrations.AlterField(
            model_name='checklisttemplate',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.CreateModel(
            name='ChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('text', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='checklists.checklisttemplate')),
            ],
            options={
                'ordering': ('template_id', 'section', 'order', 'id'),
            },
        ),
    ]
