# Generated by Django 5.2.5 on 2025-12-01 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0008_pg_idempotent_cleanup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklistrun',
            name='created_at',
        ),
        migrations.AddField(
            model_name='checklistitem',
            name='section',
            field=models.CharField(blank=True, db_index=True, default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='checklistitem',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='checklistitem',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='checklists.checklisttemplate'),
        ),
        migrations.AlterField(
            model_name='checklistrun',
            name='started_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='checklistrun',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='checklists.checklisttemplate'),
        ),
        migrations.AlterField(
            model_name='checklisttemplate',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
