# Generated by Django 6.0.1 on 2026-01-17 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0009_remove_checklistrun_created_at_checklistitem_section_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistrun',
            name='completed_pdf',
            field=models.FileField(blank=True, help_text='Upload the completed checklist PDF', null=True, upload_to='completed_checklists/'),
        ),
    ]
