# Generated by Django 6.0.1 on 2026-01-19 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0010_checklistrun_completed_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistitem',
            name='required',
            field=models.BooleanField(default=True),
        ),
    ]
