# Generated by Django 6.0.1 on 2026-01-19 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0011_checklistitem_required'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddField(
                    model_name="checklistitem",
                    name="kit_items",
                    field=models.TextField(blank=True, default=""),
                ),
            ],
        ),
    ]