# Generated by Django 6.0.1 on 2026-03-05 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0014_force_text_columns'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklistitem',
            name='section',
            field=models.CharField(blank=True, db_index=True, default='', max_length=120),
        ),
    ]
