# Generated by Django 5.2.5 on 2025-08-21 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenancePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('type', models.CharField(choices=[('time', 'Time'), ('usage', 'Usage'), ('condition', 'Condition')], default='time', max_length=16)),
                ('scope', models.JSONField(default=dict)),
                ('interval_days', models.IntegerField(blank=True, null=True)),
                ('window_days', models.IntegerField(default=10)),
                ('counter', models.CharField(blank=True, max_length=32)),
                ('interval_units', models.IntegerField(blank=True, null=True)),
                ('threshold', models.JSONField(blank=True, null=True)),
                ('priority', models.CharField(default='P2', max_length=4)),
                ('checklist_id', models.CharField(blank=True, max_length=120)),
                ('docs_url', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
