# Generated by Django 5.2.5 on 2025-09-26 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0002_add_site_published_and_backfill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancepolicy',
            name='counter',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='maintenancepolicy',
            name='scope',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='maintenancepolicy',
            name='window_days',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
