# Generated by Django 5.2.5 on 2025-11-20 01:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0009_remove_checklistrun_created_at_checklistitem_section_and_more.py'),
        ('policies', '0003_alter_maintenancepolicy_counter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancepolicy',
            name='checklist_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='policies', to='checklists.checklisttemplate'),
        ),
    ]
