# Generated by Django 5.2.5 on 2025-12-01 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0009_remove_checklistrun_created_at_checklistitem_section_and_more'),
        ('policies', '0004_maintenancepolicy_checklist_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancepolicy',
            name='checklist_template',
            field=models.ForeignKey(blank=True, help_text='Person responsible for this maintenance policy.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='policies', to='checklists.checklisttemplate'),
        ),
    ]
