# Generated by Django 5.2.5 on 2025-12-01 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0009_remove_checklistrun_created_at_checklistitem_section_and_more'),
        ('fleet', '0007_alter_robot_serial'),
        ('policies', '0005_alter_maintenancepolicy_checklist_template'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maintenancepolicy',
            options={'ordering': ('name',)},
        ),
        migrations.AddField(
            model_name='maintenancepolicy',
            name='payloads',
            field=models.ManyToManyField(blank=True, help_text='Payloads this policy applies to.', related_name='maintenance_policies', to='fleet.payload'),
        ),
        migrations.AddField(
            model_name='maintenancepolicy',
            name='robots',
            field=models.ManyToManyField(blank=True, help_text='Robots this policy applies to.', related_name='maintenance_policies', to='fleet.robot'),
        ),
        migrations.AlterField(
            model_name='maintenancepolicy',
            name='checklist_template',
            field=models.ForeignKey(blank=True, help_text='Checklist template associated with this policy.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='policies', to='checklists.checklisttemplate'),
        ),
    ]
