# Generated by Django 5.2.5 on 2025-12-05 20:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('policies', '0006_alter_maintenancepolicy_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancepolicy',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='Primary person responsible for this policy.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_maintenance_policies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='maintenancepolicy',
            name='owner_group',
            field=models.ForeignKey(blank=True, help_text='Group that owns this policy (e.g. Site Managers).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_policies', to='auth.group'),
        ),
    ]
