# Generated by Django 6.0.1 on 2026-01-18 07:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0007_maintenancepolicy_owner_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(upload_to='maintenance_records/%Y/%m/%d/')),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='policies.maintenancepolicy')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_maintenance_records', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
