# Generated by Django 6.0.1 on 2026-01-26 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0008_maintenancerecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancepolicy',
            name='last_reminded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maintenancepolicy',
            name='next_reminder_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
