# Generated by Django 5.2.5 on 2025-08-21 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('tz', models.CharField(default='UTC', max_length=64)),
                ('address', models.TextField(blank=True)),
                ('flags', models.JSONField(default=dict)),
                ('slack_channel', models.CharField(blank=True, max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Robot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=60)),
                ('serial', models.CharField(max_length=60, unique=True)),
                ('tier', models.CharField(default='P2', max_length=4)),
                ('environment', models.JSONField(default=dict)),
                ('status', models.CharField(default='active', max_length=32)),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='fleet.site')),
            ],
        ),
    ]
