# Generated by Django 5.2.5 on 2025-09-04 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='robot',
            name='environment',
        ),
        migrations.AddField(
            model_name='robot',
            name='environments',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='site',
            name='flags',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
