# Generated by Django 5.2.5 on 2025-09-11 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0002_remove_robot_environment_robot_environments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='robot',
            name='last_maintained',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='robot',
            name='environments',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
