# Generated by Django 5.2.5 on 2025-09-26 21:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0003_robot_last_maintained_alter_robot_environments'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_groups', to='fleet.site')),
                ('users', models.ManyToManyField(blank=True, related_name='client_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('site__name', 'name'),
                'unique_together': {('site', 'name')},
            },
        ),
    ]
