# Generated by Django 5.2.5 on 2025-10-09 23:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0004_clientgroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Payload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('type', models.CharField(blank=True, max_length=60)),
            ],
        ),
        migrations.AlterModelOptions(
            name='clientgroup',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='clientgroup',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='robot',
            name='last_maintained',
        ),
        migrations.AddField(
            model_name='robot',
            name='licenses',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='robot',
            name='location',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='robot',
            name='robot_type',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='robot',
            name='environments',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='site',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='site',
            name='flags',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='site',
            name='name',
            field=models.CharField(max_length=120, unique=True),
        ),
        migrations.AddField(
            model_name='robot',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='robots', to='fleet.contact'),
        ),
        migrations.AddField(
            model_name='robot',
            name='payloads',
            field=models.ManyToManyField(blank=True, to='fleet.payload'),
        ),
    ]
