# Generated by Django 5.2.5 on 2025-10-20 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0005_contact_payload_alter_clientgroup_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payload',
            name='type',
        ),
        migrations.AlterField(
            model_name='robot',
            name='payloads',
            field=models.ManyToManyField(blank=True, related_name='robots', to='fleet.payload'),
        ),
    ]
