# Generated by Django 5.2.5 on 2025-10-21 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0006_remove_payload_type_alter_robot_payloads'),
    ]

    operations = [
        migrations.AlterField(
            model_name='robot',
            name='serial',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
