# Generated by Django 5.2.5 on 2025-09-18 01:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0003_rename_updated_at_checklistrun_created_at'),
        ('notifications', '0001_initial'),
        ('policies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationlog',
            name='checklist_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='checklists.checklistrun'),
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='checklist_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='checklists.checklisttemplate'),
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='maintenance_policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='policies.maintenancepolicy'),
        ),
    ]
