# Generated by Django 5.2.5 on 2025-09-23 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0003_rename_updated_at_checklistrun_created_at'),
        ('notifications', '0002_notificationlog_checklist_run_and_more'),
        ('policies', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['channel', 'status'], name='notificatio_channel_f70f70_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['created_at'], name='notificatio_created_01830a_idx'),
        ),
    ]
